Test 01:
	g++ -std=c++11 hash_table.cpp -o hash_table
	./hash_table
	rm -f hash_table *.o

count:
	g++ -std=c++11 count.cpp -o count
	./count
	rm -f count *.o

ascii:
	g++ -std=c++11 ascii.cpp -o ascii
	./ascii
	rm -f ascii *.o

clean:
	rm -f hash_table *.o