test:
	clang++ -std=c++11 main.cpp -o main
	./main
	rm -f main *.o

arr:
	clang++ -std=c++11 arr.cpp -o main
	./main
	rm -f main *.o

rec:
	clang++ -std=c++11 rec.cpp -o main
	./main
	rm -f main *.o

clean:
	rm -f main *.o