test:
	clang++ -std=c++11 main.cpp -o main
	./main
	rm -f main *.o

iteration:
	clang++ -std=c++11 iteration.cpp -o main
	./main
	rm -f main *.o

best:
	clang++ -std=c++11 best.cpp -o main
	./main
	rm -f main *.o


clean:
	rm -f main *.o