Test 01:
	clang++ -std=c++11 dp.cpp -o main
	./main
	rm -f main *.o

dp2:
	clang++ -std=c++11 dp2.cpp -o main
	./main
	rm -f main *.o

dc:
	clang++ -std=c++11 dc.cpp -o main
	./main
	rm -f main *.o


clean:
	rm -f main *.o