Test 01:
	g++ -std=c++11 main.cpp -o main
	./main
	rm -f main *.o

bt:
	g++ -std=c++11 backtrack.cpp -o main
	./main
	rm -f main *.o

dfs:
	g++ -std=c++11 dfs.cpp -o main
	./main
	rm -f main *.o


clean:
	rm -f main *.o