Test 01:
	clang++ -std=c++11 main.cpp -o main
	./main
	rm -f main *.o

sort:
	clang++ -std=c++11 sort.cpp -o main
	./main
	rm -f main *.o

hash:
	clang++ -std=c++11 hash.cpp -o main
	./main
	rm -f main *.o

clean:
	rm -f main *.o